package storage

import (
	"context"
	"time"

	"github.com/d1agnozzz/url-shortener/internal/types"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type postgresStorage struct {
	db *pgxpool.Pool
}

func NewPostgresStorage(ctx context.Context, conStr string) (Storage, error) {
	conn, err := pgxpool.New(ctx, conStr)

	if err != nil {
		return nil, err
	}

	if err := conn.Ping(ctx); err != nil {
		return nil, err
	}

	storage := postgresStorage{
		db: conn,
	}

	storage.init(ctx)

	return &storage, nil
}

func (s *postgresStorage) init(ctx context.Context) error {
	return s.createUrlsTable(ctx)

}

func (s *postgresStorage) createUrlsTable(ctx context.Context) error {

	query := `CREATE TABLE IF NOT EXISTS url_aliases (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY,
		url TEXT NOT NULL CHECK (LENGTH(url) <= 2000),
		alias TEXT NOT NULL CHECK (LENGTH(alias) <= 10),
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		CONSTRAINT unique_url UNIQUE (url),
		CONSTRAINT unique_alias UNIQUE (alias)

	)`

	_, err := s.db.Exec(ctx, query)
	return err
}

func (s *postgresStorage) InsertURLMapping(ctx context.Context, urlMapping types.URLMapping) error {
	_, err := s.db.Exec(ctx, "INSERT INTO url_aliases(url, alias) values ($1, $2)", urlMapping.Url, urlMapping.Alias)

	if err != nil {
		return err
	}
	return nil
}

func (s *postgresStorage) GetByAlias(ctx context.Context, alias string) (*types.URLMapping, error) {
	row := s.db.QueryRow(ctx, "SELECT * FROM url_aliases WHERE alias=$1", alias)

	urlMapping, err := scanURLMapping(row)

	if err != nil {
		return nil, err
	}

	return urlMapping, nil
}

func scanURLMapping(row pgx.Row) (*types.URLMapping, error) {
	var (
		id        int64
		url       string
		alias     string
		createdAt time.Time
	)

	err := row.Scan(&id, &url, &alias, &createdAt)

	if err != nil {
		return nil, err
	}

	return &types.URLMapping{
		Id:        id,
		Url:       url,
		Alias:     alias,
		CreatedAt: createdAt,
	}, nil

}
